quarkus:
  application:
    name: transaction-service

  http:
    port: 8084

  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: admin
    password: "123456"
    reactive:
      url: postgresql://postgres:5432/transaction_db
      max-size: 20

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true

  swagger-ui:
    always-include: true
    path: /swagger-ui

  rest-client:
    account-service:
      url: http://account-service:8085
      scope: jakarta.inject.Singleton
    customer-service:
      url: http://customer-service:8083
      scope: jakarta.inject.Singleton
    bcrp-service:
      url: http://bcrp-simulator:8086
      scope: jakarta.inject.Singleton

mp:
  messaging:
    outgoing:
      audit-events:
        connector: smallrye-kafka
        topic: audit-events
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  bootstrap:
    servers: kafka:9092