quarkus:
  application:
    name: api-gateway

  http:
    port: 8080
    cors:
      ~: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: accept,authorization,content-type

  swagger-ui:
    always-include: true
    path: /swagger-ui
    title: API Gateway - Sistema BCRP

  rest-client:
    customer-service:
      url: http://customer-service:8083
      scope: jakarta.inject.Singleton
    account-service:
      url: http://account-service:8085
      scope: jakarta.inject.Singleton
    transaction-service:
      url: http://transaction-service:8084
      scope: jakarta.inject.Singleton
    bcrp-service:
      url: http://bcrp-simulator:8086
      scope: jakarta.inject.Singleton
    audit-service:
      url: http://audit-service:8088
      scope: jakarta.inject.Singleton