quarkus:
  application:
    name: customer-service

  http:
    port: 8083

  datasource:
    # DESHABILITAR DEV SERVICES
    devservices:
      enabled: false
    # CONFIGURACIÓN POSTGRESQL
    db-kind: postgresql
    username: admin
    password: "123456"
    reactive:
      url: postgresql://localhost:5432/customer_db
      max-size: 20

  hibernate-orm:
    database:
      generation: update #drop-and-create
    log:
      sql: true

  swagger-ui:
    always-include: true
    path: /swagger-ui